### ISSUE TITLE
Editing default values on inputs is broken

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/tangelohub#135]
For example, Fit continuous in Arbor collection on arbor.kitware.com has an input with a default value:

```json
        {
            "default": {
                "data": "BM",
                "format": "text"
            },
            "domain": [
                "BM",
                "OU",
                "EB"
            ],
            "format": "text",
            "name": "model",
            "type": "string"
        }
```

When editing that input the dialog shows a bad value for Default:

![screen shot 2015-05-07 at 2 11 07 pm](https://cloud.githubusercontent.com/assets/81305/7522407/03629336-f4c3-11e4-8e28-cbe213b8b173.png)

**Comment by zackgalbreath** [comment]
Addressed by https://github.com/Kitware/tangelohub/pull/141.
