### ISSUE TITLE
Error storing tables in collections - new girder model problem

### ISSUE THREAD

**Issue by curtislisle** [Kitware/tangelohub#145]
Recently, new dataset save errors are occurring frequently for me.  When I tried to save a table to a public collection (Hackathon May 2015), a long delay (15 seconds) occurs, then the following appears in the JS console:

Uncaught TypeError: Cannot set property type of #<Blob> which has only a getter
girder.models.FileModel.girder.Model.extend._uploadToContainer @ FileModel.js:55
girder.models.FileModel.girder.Model.extend.uploadToFolder @ FileModel.js:68
window.flow.girderUpload @ util.js:253

**Comment by jeffbaumes** [comment]
What browser and version are you on? I can see a bug in the Girder code that could be causing this - though I cannot reproduce that error on my Safari, Chrome, or Firefox. Try another browser to see if that works around your issue.

See girder/girder#829

**Comment by curtislisle** [comment]
weird!  thanks for looking into this.  I’m glad it seems to only be happening to me. I was worried that many users would not be able to save into collections.  My results seem to indicate older Chrome versions are more forgiving:

On OSX 10.9:
the error occurs on Chrome Version 43.0.2357.52 beta (64-bit)

in Safari Version 7.1.6 (9537.85.15.3), I get a similar sounding error:  
	TypeError: Attempted to assign to readonly property.  (girder/FileModel.js: line 55)

It might be my older or beta model browsers.

On OSX 10.10:
with Chrome 42.0.2311, no error and the copy operation was successful..  

On Linux:
I also see the error on Chrome for Linux v 44
It works on Chrome for Linux v 41

**Comment by curtislisle** [comment]
This has been merged into #150
