### ISSUE TITLE
can ansible script install romanesco as service that automatically respawns?

### ISSUE THREAD

**Issue by curtislisle** [Kitware/tangelohub#161]
Often, when writing experimental workflows or analyses, I need to manually restart romanesco.  Can the ansible script install romanesco as a service that restarts when it fails?

**Comment by jeffbaumes** [comment]
Yes, it could. I have supervisor auto restarting romanesco for arbor.kitware.com. If processes hang, I still sometimes need to manually restart romanesco, but it is much better than what is standard.

Not sure if there is a quick fix for the upstart scripts in ansible to allow restarts. @zachmullen @zackgalbreath any experience with upstart or can someone look at fixing this another way?

**Comment by opadron** [comment]
Have a look [here[(https://github.com/Kitware/gobig/blob/master/roles/upstart/templates/service.conf.j2#L7-L8) (taken from the upstart ansible role in gobig).  I hope this is helpful.

**Comment by jeffbaumes** [comment]
Looks like that would work and would be fairly simple. @zachmullen could you take a look and implement?
