### ISSUE TITLE
Consistently use Girder's JavaScript utility for using REST API

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/tangelohub#28]
Changes to Girder, like requiring a token in a special header, currently break TangeloHub on calls that do not use Girder's utility function. Should replace all d3 or jQuery ajax calls to use the Girder library function.

**Comment by zackgalbreath** [comment]
Using ``git grep`` I've verified that we aren't using any of the following methods:
``d3.json() $.get() $.post() $.ajax()``

The only remaining suspicion I have is our use of ``girder.apiRoot``:

https://github.com/Kitware/tangelohub/blob/master/app/src/views/AnalysisSetupView.js#L29
https://github.com/Kitware/tangelohub/blob/master/app/src/views/InputsView.js#L96
https://github.com/Kitware/tangelohub/blob/master/app/src/views/WorkflowInputsView.js#L56
https://github.com/Kitware/tangelohub/blob/master/app/src/views/WorkflowView.js#L52

These lines of code appear to be copied & pasted, so even if we can't replace them with ``girder.restRequest`` perhaps we could encapsulate them to eliminate this repetition.

``girder.apiRoot`` is also used to enable streaming output from our analyses.  I don't think there's any way we could replicate this behavior using ``girder.restRequest``.
https://github.com/Kitware/tangelohub/blob/master/app/src/views/AnalysisSetupView.js#L78

**Comment by jeffbaumes** [comment]
There is definitely some code duplication that should be avoided here in the first two files. The WorkflowInputsView and WorkflowView code is actually not used - it was a potential new interface I wrote a while back whose code still lingers - so I wouldn't spend time on that. Looks like in one place we are using the `token=` argument, and in the other we are using the `Girder-Token` header. This may be the difference between old-style and new-style Romanesco data reference specs. @zachmullen can you suggest what is the best approach - perhaps suggest a common function that will work in both places?

I also see what I think is a bug on this line:

https://github.com/Kitware/tangelohub/blob/master/app/src/views/InputsView.js#L98

I'm pretty convinced that `dataset.uri` should just be `uri` since `dataset.uri` will just be immediately overwritten - although it may be that it should all be moved over to use the `Girder-Token` header anyway.

**Comment by zachmullen** [comment]
The token can be passed either as a query or form parameter called `token`, or using the `Girder-Token` header. It is recommended that it be passed via the header whenever possible. The functionality is equivalent, so we should just convert to using the way shown in https://github.com/Kitware/tangelohub/blob/master/app/src/views/AnalysisSetupView.js#L29 everywhere.

It could be easily wrapped in a reusable function:

```
var girderItemInput = function(itemId) {
    return {
        mode: 'http',
        url: window.location.origin + girder.apiRoot + '/item/' + itemId + '/download',
        method: 'GET',
        headers: girder.currentUser ? {
            'Girder-Token': girder.currentUser.get('token')
        } : {}
    };
};
```

**Comment by jeffbaumes** [comment]
Thanks. @zackgalbreath can you incorporate this change and make this utility function? There may be a larger chunk of code surrounding the data URL logic that could be reused in both places - but this is a good start.

**Comment by zackgalbreath** [comment]
Sure, this change is available here: https://github.com/Kitware/tangelohub/pull/117

I've verified that AnalysisSetupView still behaves correctly.  Can you give me an example of how to exercise InputsView?

**Comment by jeffbaumes** [comment]
Looks like `values()` is only called in `InputsView` when it is used to generate the Add Input or Add Output dialog - which never uses dataset options. We could/should change AnalysisSetupView to call `values()` and remove similar logic in AnalysisSetupView.

**Comment by jeffbaumes** [comment]
Your call to make that change now or merge and open a new issue - does not seem too tough to make the change now.

**Comment by zachmullen** [comment]
On this subject, when possible it would actually be best to use girder's model layer rather than call `girder.restRequest` directly. I've already taken care of the most extreme case here: https://github.com/Kitware/tangelohub/commit/99335290d2478533a24396de5cb52f31a6e50a7e

**Comment by jeffbaumes** [comment]
Agreed @zachmullen. Not sure if we can remove `girder.restRequest` entirely (Romanesco calls etc.) but another issue where we seek to minimize its use would be good. Could you open this issue?
