### ISSUE TITLE
Manually specify whether there are column headers

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/tangelohub#31]
User should be able to specify this on per-file basis, or let it do auto-detection. Will require changes to Romanesco and TangeloHub UI. One option is to have formats "csv" (with header) and "csv.nohead" (without header). This may also mean TangeloHub needs to be able to specify whether Romanesco should do header detection if nothing specified by user, or to just assign the type specified by the user. Splitting out header detection (i.e. format sniffing) as a separate Romanesco operation seems like the right approach.

**Comment by curtislisle** [comment]
Until we can get to a more complete solution, we should change line # 114 to "if True" to disable CSV sniffing happening in an undesirable way:

https://github.com/Kitware/romanesco/blob/master/romanesco/format/__init__.py

**Comment by jeffbaumes** [comment]
We now just assume there are column headers. Closing this for now.
